# -*- coding: utf-8 -*-
"""Task_3_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UcH-gY6z1zNg3cKAH7xnhR9N5Erhz8h1

# Пример восстановления исходного изображения размером 200х200 пикселей по первым десяти ГК, если известны матрица счётов и матрица весов.

Для восстановления исходного изображения воспользуемся матрицами счётов и весов.
"""

#Импорт библиотеки Numpy
import numpy as np 
#Создание массивов Numpy на основе матриц счётов и весов
scores = np.genfromtxt('X_reduced_401.csv', delimiter=';')
loadings = np.genfromtxt('X_loadings_401.csv', delimiter=';')

"""Найдем матрицу восстановленных данных как произведение матрицы счётов на транспонированную матрицу весов. """

values = np.dot(scores,loadings.T)

"""Создадим изображение на основе полученных значений при помощи библиотеки matplotlib"""

# Commented out IPython magic to ensure Python compatibility.
#Импорт библиотеки
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline
#Создание изображения
plt.imshow(values, cmap='Greys_r')